# Generated by Django 3.2 on 2022-01-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_people_facultytype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Faculty_Advisors',
        ),
    ]
