# Generated by Django 3.2 on 2022-02-04 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_faculty_advisors_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_advisors',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='faculty_advisors',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
