# Generated by Django 3.2 on 2022-02-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220204_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_advisors',
            old_name='imgdesc',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='faculty_advisors',
            old_name='imgtitle',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='faculty_advisors',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
