# Generated by Django 3.2 on 2022-02-04 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_faculty_advisors_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_advisors',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
