# Generated by Django 3.2 on 2022-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_faculty_advisors_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_advisors',
            name='domain',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AddField(
            model_name='faculty_advisors',
            name='education',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
