# Generated by Django 3.2 on 2022-02-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220204_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_advisors',
            old_name='education',
            new_name='phd',
        ),
    ]
