# Generated by Django 3.2 on 2022-02-04 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_education_faculty_advisors_phd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=700)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(upload_to='images/')),
                ('StaffType', models.CharField(blank=True, choices=[('TechnicalStaff', 'TechnicalStaff'), ('Administrative Staff', 'Administrative Staff')], max_length=60)),
                ('phoneNumber', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
    ]
