# Generated by Django 3.2 on 2022-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_PhdStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DegreeType_Recent', models.CharField(max_length=700)),
                ('DomainOfStudy', models.CharField(max_length=900)),
                ('CollegeName', models.CharField(max_length=900)),
                ('CollegePassingYear', models.IntegerField()),
                ('Supervisor', models.CharField(max_length=900)),
                ('ResearchArea', models.CharField(max_length=900)),
            ],
        ),
    ]
