# Generated by Django 3.2 on 2022-03-12 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_graduated_phdstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_advisors',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='((\\+*)((0[ -]*)*|((91 )*))((\\d{12})+|(\\d{10})+))|\\d{5}([- ]*)\\d{6}')]),
        ),
    ]
