# Generated by Django 3.2 on 2022-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_faculty_advisors_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_advisors',
            name='phoneNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneNumber',
            field=models.TextField(),
        ),
    ]
