# Generated by Django 3.2 on 2022-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220312_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResearchArea', models.CharField(default='ResearchArea', max_length=255)),
                ('CurrentResearchThemes', models.TextField(default='ResearchThemes')),
                ('ResearchLabs', models.TextField(default='ResearchLabs')),
                ('Faculty', models.TextField(default='Faculty')),
            ],
        ),
    ]
