# Generated by Django 3.2 on 2022-03-25 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220325_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2022, 3, 25))),
                ('Time', models.TimeField(default=datetime.time(18, 0, 46, 582604))),
                ('Speaker', models.CharField(default='Name of Speaker', max_length=50)),
                ('Title', models.CharField(default='Title of talk', max_length=200)),
                ('Abstract', models.TextField(default='Abstract of Talk')),
                ('image', models.ImageField(default='images/11.jpg', upload_to='images/')),
            ],
        ),
    ]
