# Generated by Django 3.2 on 2022-03-25 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_upcomingwebinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingStudentPPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2022, 3, 25))),
                ('Time', models.TimeField(default=datetime.time(18, 24, 2, 783554))),
                ('Presenter', models.CharField(default='Name of Speaker', max_length=50)),
                ('Topic', models.CharField(default='Title of talk', max_length=200)),
                ('image', models.ImageField(default='images/11.jpg', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(18, 24, 2, 782557)),
        ),
    ]
