# Generated by Django 3.2 on 2022-03-31 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20220325_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 3, 31)),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(9, 56, 29, 989541)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 3, 31)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(9, 56, 29, 988546)),
        ),
    ]
