# Generated by Django 3.2 on 2022-03-31 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220331_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='CompletionYear',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='TechnologyTrack',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(10, 1, 24, 831885)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(10, 1, 24, 830886)),
        ),
    ]
