# Generated by Django 3.2 on 2022-03-31 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20220331_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_advisors',
            name='FacultyType',
            field=models.CharField(blank=True, choices=[('RegularFaculty', 'RegularFaculty'), ('YoungFacultyAssociates', 'YoungFacultyAssociates'), ('GuestFaculty', 'GuestFaculty'), ('AdjunctFaculty', 'AdjunctFaculty'), ('ScholarsinResidence', 'ScholarsinResidence'), ('Advisors', 'Advisors'), ('FormerFaculty', 'FormerFaculty')], max_length=60),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 33, 4, 625302)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 33, 4, 609672)),
        ),
    ]
