# Generated by Django 3.2 on 2022-03-31 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20220331_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='staff',
            name='Education',
            field=models.TextField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 39, 30, 396908)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 39, 30, 396908)),
        ),
    ]
