# Generated by Django 3.2 on 2022-04-03 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20220331_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=900)),
                ('Roll', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=400)),
                ('CourseWorkStatus', models.CharField(max_length=400)),
                ('Supervisior', models.CharField(max_length=400)),
                ('PreviousTAship', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 3)),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 50, 15, 339450)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 3)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 50, 15, 339450)),
        ),
    ]
