# Generated by Django 3.2 on 2022-04-12 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220403_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment', models.CharField(max_length=400)),
                ('Installation_Location', models.CharField(max_length=100)),
                ('PI_Project', models.CharField(max_length=400)),
                ('PI', models.CharField(max_length=400)),
                ('Last_maintainence_date', models.CharField(max_length=400)),
                ('Details', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='ta',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 13)),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(1, 42, 51, 970107)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 13)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(1, 42, 51, 969082)),
        ),
    ]
