# Generated by Django 3.2 on 2022-04-14 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220413_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Authors', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=400)),
                ('Journal', models.CharField(max_length=100)),
                ('Vol', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('DOI', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(16, 20, 8, 5811)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(16, 20, 8, 5811)),
        ),
    ]
