# Generated by Django 3.2 on 2022-04-14 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20220414_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyName', models.CharField(max_length=50)),
                ('AwardName', models.CharField(max_length=200)),
                ('AwardingBody', models.CharField(max_length=400)),
                ('Year', models.IntegerField()),
                ('Details', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(18, 41, 9, 726028)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(18, 41, 9, 726028)),
        ),
    ]
