# Generated by Django 3.2 on 2022-05-06 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20220502_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlist',
            name='Vol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 5, 6)),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(11, 43, 17, 366830)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 5, 6)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(11, 43, 17, 366830)),
        ),
    ]
