# Generated by Django 3.2 on 2022-05-06 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20220506_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlist',
            name='DOI',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationlist',
            name='Year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(11, 47, 0, 784294)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(11, 47, 0, 784294)),
        ),
    ]
