# Generated by Django 3.2 on 2022-05-06 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20220506_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlist',
            name='Year',
            field=models.IntegerField(verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='upcomingstudentppt',
            name='Time',
            field=models.TimeField(default=datetime.time(11, 54, 18, 611234)),
        ),
        migrations.AlterField(
            model_name='upcomingwebinar',
            name='Time',
            field=models.TimeField(default=datetime.time(11, 54, 18, 611234)),
        ),
    ]
