from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("academic/", views.academic, name="academic"),
    path("people/faculty_advisors/", views.faculty_advisors, name="faculty_advisors"),
    path("people/staff/TechnicalStaff/", views.technicalstaff, name="TechnicalStaff"),
    path("people/staff/AdministrativeStaff/", views.administrativestaff, name="Administrative Staff"),
    path("people/Phd_students/", views.Phd_students, name="phd_students"),
    path("research/", views.research, name="research"),
    path("ResearchAreas/", views.researchAreas, name="ResearchAreas"),
    path("Cell&MolecularPhysiology/", views.CellandMolecularPhysiology, name="Cell&MolecularPhysiology"),
    path("EnvironmentalBiotechnology/", views.EnvironmentalBiotechnology, name="EnvironmentalBiotechnology"),
    path("BiomaterialsandTissueEngineering/", views.BiomaterialsandTissueEngineering, name="BiomaterialsandTissueEngineering"),
    path("ChemicalBiologyandDrugDesign/", views.ChemicalBiologyandDrugDesign, name="ChemicalBiologyandDrugDesign"),
    path("MolecularMicrobiology&MicrobialGenomics/", views.MolecularMicrobiologyandMicrobialGenomics, name="MolecularMicrobiology&MicrobialGenomics"),
    path("Biophysics/", views.Biophysics, name="Biophysics"),
    path("Neuroscience&Neuroengineering/", views.NeuroscienceandNeuroengineering, name="Neuroscience&Neuroengineering"),
    path("MolecularMotors&CellMotility/", views.MolecularMotorsandCellMotility, name="MolecularMotors&CellMotility"),
    path("ComputationalBiology&Bioinformatics/", views.ComputationalBiologyandBioinformatics, name="ComputationalBiology&Bioinformatics"),
    path("Projects/", views.projects, name="Projects"),
    path("Sponsers&Collaborators/", views.SponsandColab, name="Sponsers&Collaborators"),
    path("researchlabs/", views.researchlabs, name="researchlabs"),
    path("events/webinars", views.webinars, name="webinars"),
    path("events/students_presentation", views.upcomingstudentppt, name="students_presentation"),
    #path("events/students_presentation", views.students_presentation, name="students_presentation"),
    #path("/OngoingProjects/",views.ongoingprojects,)
    path("students/placements", views.placements, name="placements"),
    path("students/acm_student_chapter_iitj", views.acm_student_chapter_iitj, name="acm_student_chapter_iitj"),
    path("students/alumni", views.alumni, name="alumni"),
    path("students/club_activity", views.club_activity, name="club_activity"),
    path("joinus/", views.joinus, name="joinus"),
    path("contacts/", views.contacts, name="contacts"),
    path("pubmed/", views.pubmed, name="pubmed"),
    path("allresearch/", views.allresearch, name="allresearch"),
    path("allnews/", views.allnews, name="allnews"),
    path("intranet/students", views.Students, name="students"),
    path("intranet/equipment", views.AparatusDetails, name="equipment"),
    path("intranet/ta", views.TeachingAssistant, name="intranetTA"),
    path("BTech in Bioscience and Bioengineering/",views.Btechug,name="BTech in Bioscience and Bioengineering"),
    path("MTech in Bioengineering/",views.Mtechpg,name="MTech in Bioengineering"),
    path("PhD in Bioengineering/",views.PhDpg,name="PhD in Bioengineering"),
    path("AllFaculties/Publications", views.Publications, name="Publications"),
    path("AllFaculties/Awards", views.Awards, name="Awards"),
    path("AllFaculties/Projects", views.project_list, name="projects"),
    path("AllFaculties/ProjectStudents", views.projectstudent_list, name="ProjectStudents"),
]